spring:
  application:
    name: pacientes
  datasource:
    url: jdbc:postgresql://localhost:5432/paciente
    username: apex
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
server:
  error:
    include-message: always
